/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pos.inventory;

import com.ustasoft.component.GeneralFunction;
import com.ustasoft.pos.dao.jdbc.GudangDao;
import com.ustasoft.pos.domain.Gudang;
import com.ustasoft.pos.service.ReportService;
import java.sql.Connection;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pos.MainForm;

/**
 *
 * @author cak-ust
 */
public class FrmRptInventory extends javax.swing.JInternalFrame {
    private Connection conn;
    ReportService service;
    List<Gudang> gudang=new ArrayList<Gudang>();
    private GeneralFunction fn=new GeneralFunction();
    /**
     * Creates new form FrmReportInventory
     */
    public FrmRptInventory() {
        initComponents();
    }

    public void setConn(Connection con){
        this.conn=con;
        service=new ReportService(conn, this);
        fn.setConn(conn);
    }
    
    private void initForm(){
        try {
            gudang=new GudangDao(conn).cariSemuaData();
            cmbGudang.removeAllItems();
            cmbGudang.addItem("Semua Gudang");
            for(int i=0; i<gudang.size(); i++){
                cmbGudang.addItem(gudang.get(i).getNama_gudang());
            }
            Timestamp skg=fn.getTimeServer();
            jDateChooserAwal.setDate(skg);
            jDateChooserAkhir.setDate(skg);
            jList1.setSelectedIndex(0);
            
        } catch (Exception ex) {
            Logger.getLogger(FrmRptInventory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    SimpleDateFormat fmt=new SimpleDateFormat("yyyy-MM-dd");
    
    private void udfPreview(){
        int idx=jList1.getSelectedIndex();
        if(idx==2||idx==3||idx==4){
            if(txtItem1.getText().length()==0){
                JOptionPane.showMessageDialog(this, "Silahkan pilih item ke 2 terlebih dulu!");
                txtItem1.requestFocusInWindow();
                return;
            }
        }
        
        HashMap param=new HashMap();
        param.put("toko", MainForm.sToko);
        param.put("alamat1", MainForm.sAlamat1);
        param.put("alamat2", MainForm.sAlamat2);
        param.put("telp", MainForm.sTelp1);
        param.put("email", MainForm.sEmail);
        param.put("tanggal1", fmt.format(jDateChooserAwal.getDate()));
        param.put("tanggal", fmt.format(jDateChooserAwal.getDate()));
        param.put("tanggal2", fmt.format(jDateChooserAkhir.getDate()));
        param.put("idBarang", txtItem.getText());
        param.put("kodeBarang1", lblPLU.getText());
        param.put("kodeBarang2", lblPLU1.getText());
        param.put("idGudang", cmbGudang.getSelectedIndex()==0? "": gudang.get(cmbGudang.getSelectedIndex()-1).getId().toString());
        

        switch(jList1.getSelectedIndex()){
            case 0:{
                service.udfPreview(param, "KartuStok", null);
                break;
            }
            case 1:{
                service.udfPreview(param, "KartuStokPrice", null);
                break;
            }
            case 2:{
                service.udfPreview(param, "StokSaldo", null);
                break;
            }
            case 3:{
                service.udfPreview(param, "StokMutasi", null);
                break;
            }
            case 4:{
                service.udfPreview(param, "StokMutasiPerGudang", null);
                break;
            }
            case 5:{
                param.put("inOut", "IN");
                service.udfPreview(param, "StokMasukKeluar", null);
                break;
            }
            case 6:{
                param.put("inOut", "OUT");
                service.udfPreview(param, "StokMasukKeluar", null);
                break;
            }
            case 7:{
                service.udfPreview(param, "StokTransfer", null);
                break;
            }
            case 8:{
                service.udfPreview(param, "StockMonthly", null);
                break;
            }
            default:{
                break;
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooserAkhir = new com.toedter.calendar.JDateChooser();
        jDateChooserAwal = new com.toedter.calendar.JDateChooser();
        cmbGudang = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtItem = new javax.swing.JTextField();
        lblPLU = new javax.swing.JLabel();
        lblNamaBarang = new javax.swing.JLabel();
        txtItem1 = new javax.swing.JTextField();
        lblNamaBarang1 = new javax.swing.JLabel();
        lblPLU1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Laporan Persediaan");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "1.  Kartu Stok", "2.  Kartu Stok - Dengan Harga Transaksi", "3.  Daftar Saldo Stok", "4.  Mutasi Stok", "5.  Mutasi Stok Per Gudang", "6.  Penerimaan Stok", "7.  Pengeluaran Stok", "8.  Pindah Gudang", "9.  Stok Bulanan" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 269, 260));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameter"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Gudang :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 70, 20));

        jLabel2.setText("Awal :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 20));
        jPanel2.add(jDateChooserAkhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 45, 130, -1));
        jPanel2.add(jDateChooserAwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 130, -1));

        cmbGudang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TUNAI", "KREDIT" }));
        jPanel2.add(cmbGudang, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 130, -1));

        jLabel3.setText("Sampai :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 45, 70, 20));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Item"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtItemKeyReleased(evt);
            }
        });
        jPanel3.add(txtItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 40, 20));

        lblPLU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(lblPLU, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 60, 20));

        lblNamaBarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(lblNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 250, 20));

        txtItem1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtItem1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtItem1KeyReleased(evt);
            }
        });
        jPanel3.add(txtItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 40, 20));

        lblNamaBarang1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(lblNamaBarang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 45, 250, 20));

        lblPLU1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(lblPLU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 45, 60, 20));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 370, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 200));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/printer.png"))); // NOI18N
        jButton1.setText("Tampilkan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 235, 110, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/cancel.png"))); // NOI18N
        jButton2.setText("Tutup");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 235, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 11, 410, 270));

        setBounds(0, 0, 704, 312);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        initForm();
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        udfPreview();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtItemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemKeyReleased
        fn.lookup(evt, new Object[]{lblPLU, lblNamaBarang}, "select id::varchar as id, coalesce(plu,'') as plu, "
                + "coalesce(nama_barang,'') as nama_barang "
                + "from m_item i "
                + "where id::varchar||coalesce(plu,'')||coalesce(nama_barang,'') ilike '%"+txtItem.getText()+"%' "
                + "order by coalesce(plu,'')", 
                txtItem.getWidth()+lblPLU.getWidth()+lblNamaBarang.getWidth()+18, 150);
    }//GEN-LAST:event_txtItemKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtItem1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItem1KeyReleased
        fn.lookup(evt, new Object[]{lblPLU1, lblNamaBarang1}, "select id::varchar as id, coalesce(plu,'') as plu, "
                + "coalesce(nama_barang,'') as nama_barang "
                + "from m_item i "
                + "where id::varchar||coalesce(plu,'')||coalesce(nama_barang,'') ilike '%"+txtItem1.getText()+"%' "
                + "order by coalesce(plu,'') ", 
                txtItem1.getWidth()+lblPLU1.getWidth()+lblNamaBarang1.getWidth()+18, 150);
    }//GEN-LAST:event_txtItem1KeyReleased

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        int idx=jList1.getSelectedIndex();
        cmbGudang.setEnabled(idx==0||idx==1||idx==2||idx==3||idx==4||idx==5||idx==6);
        txtItem.setEnabled(idx==0||idx==1||idx==2||idx==3);
        txtItem1.setEnabled(idx==0||idx==1||idx==2||idx==3);
        jDateChooserAkhir.setEnabled(!(idx==2));
    }//GEN-LAST:event_jList1ValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbGudang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooserAkhir;
    private com.toedter.calendar.JDateChooser jDateChooserAwal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNamaBarang;
    private javax.swing.JLabel lblNamaBarang1;
    private javax.swing.JLabel lblPLU;
    private javax.swing.JLabel lblPLU1;
    private javax.swing.JTextField txtItem;
    private javax.swing.JTextField txtItem1;
    // End of variables declaration//GEN-END:variables
}
