/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pos.ap;

import pos.ar.*;
import com.ustasoft.component.GeneralFunction;
import com.ustasoft.component.MyRowRenderer;
import com.ustasoft.pos.service.ReportService;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.decorator.HighlighterFactory;
import pos.MainForm;

/**
 *
 * @author cak-ust
 */
public class FrmKartuHutangPerSupplier extends javax.swing.JInternalFrame {
    private GeneralFunction fn=new GeneralFunction();
    ReportService service;
    private Connection conn;
    /**
     * Creates new form FrmKartuPiutang
     */
    public FrmKartuHutangPerSupplier() {
        initComponents();
        jXTable1.setHighlighters(HighlighterFactory.createAlternateStriping());
        txtSupplier.addFocusListener(txtFocusListener);
        for (int i = 0; i < jXTable1.getColumnCount(); i++) {
            jXTable1.getColumn(i).setCellRenderer(new MyRowRenderer());
        }
        jXTable1.getColumnExt("ApID").setVisible(false);
        jXTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                int iRow=jXTable1.getSelectedRow();
                btnBayar.setEnabled(iRow>=0 && 
                        fn.udfGetDouble(jXTable1.getValueAt(iRow, jXTable1.getColumnModel().getColumnIndex("Nilai Faktur"))) > fn.udfGetDouble(jXTable1.getValueAt(iRow, jXTable1.getColumnModel().getColumnIndex("Bayar"))));
            }
        });
    }

    public void setConn(Connection c){
        this.conn=c;
        jXDatePicker1.setFormats(MainForm.sDateFormat);
        jXDatePicker2.setFormats(MainForm.sDateFormat);
        service=new ReportService(conn, this);
    }
    
    private void bayar(){
        FrmApPayment f1 = new FrmApPayment();
        MainForm.jDesktopImage2.add(f1);
        f1.setBounds(0, 0, f1.getWidth(), f1.getHeight());
        f1.setConn(conn);
        f1.setJtTempo(true);
        f1.setId(fn.udfGetInt(jXTable1.getValueAt(jXTable1.getSelectedRow(), jXTable1.getColumnModel().getColumnIndex("ApID"))));
        f1.setSrcForm(this);
        f1.setVisible(true);
    }
    
    private void udfLoadData(String s){
        String query="select * from fn_rpt_kartu_tagihan_hutang("
                + "'"+fn.yyyymmdd_format.format(jXDatePicker1.getDate())+"', "
                + "'"+fn.yyyymmdd_format.format(jXDatePicker2.getDate())+"', "
                + fn.udfGetInt(txtSupplier.getText())+ ") as (id bigint, keterangan varchar, invoice_no varchar, \n" +
                    "tanggal date, invoice_amount double precision, paid_amount double precision, owing double precision, \n" +
                    "bayar double precision, tgl_bayar date, alat_bayar varchar, akun varchar, ket_pembayaran text)";
        System.out.println(query);
        ((DefaultTableModel)jXTable1.getModel()).setNumRows(0);
        try {
            ResultSet rs=conn.createStatement().executeQuery(query);
            int i=1, row=0;
            while(rs.next()){
                ((DefaultTableModel)jXTable1.getModel()).addRow(new Object[]{
                    i,
                    rs.getDate("tanggal"),
                    rs.getString("invoice_no"),
                    rs.getDouble("invoice_amount"),
                    rs.getDate("tgl_bayar"),
                    rs.getDouble("bayar"),
                    rs.getString("alat_bayar"),
                    rs.getString("akun"),
                    rs.getString("ket_pembayaran"),
                    rs.getInt("id")
                });
                i++;
            }
            rs.close();
            if(jXTable1.getRowCount() >0){
                jXTable1.setRowSelectionInterval(row, row);
                jXTable1.setModel(fn.autoResizeColWidth(jXTable1, ((DefaultTableModel)jXTable1.getModel())).getModel());
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmKartuPiutang.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtSupplier = new javax.swing.JTextField();
        lblCustomer = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        jButton2 = new javax.swing.JButton();
        btnBayar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Kartu Hutang per Supplier");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel3.setText("Mulai Tgl.");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(15, 35, 90, 20);

        txtSupplier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSupplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSupplierKeyReleased(evt);
            }
        });
        jPanel2.add(txtSupplier);
        txtSupplier.setBounds(105, 10, 60, 20);

        lblCustomer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblCustomer);
        lblCustomer.setBounds(165, 10, 410, 20);

        jLabel4.setText("Supplier :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(15, 10, 90, 20);
        jPanel2.add(jXDatePicker1);
        jXDatePicker1.setBounds(105, 35, 115, 22);
        jPanel2.add(jXDatePicker2);
        jXDatePicker2.setBounds(320, 35, 115, 22);

        jLabel5.setText("Sampai :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(230, 35, 90, 20);

        jButton1.setText("Tampilkan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(465, 35, 115, 23);

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Tanggal", "No. Invoice", "Nilai Faktur", "Tgl Bayar", "Bayar", "Alat Bayar", "Kas/ Bank", "Keterangan", "ApID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jXTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jXTable1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/printer.png"))); // NOI18N
        jButton2.setText("Cetak");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnBayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/drawer.png"))); // NOI18N
        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(5, 5, 5))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnBayar)))
        );

        setBounds(0, 0, 631, 387);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSupplierKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierKeyReleased
        String sQry="select id_relasi::varchar as id_customer, coalesce(nama_relasi,'') as nama_customer, "
        + "alamat||' - '||kota.nama_kota as alamat, coalesce(s.top,0) as top "
        + "from m_relasi s "
        + "left join m_kota kota on kota.id=s.id_kota "
        + "where tipe_relasi=1 and id_relasi::varchar||coalesce(nama_relasi,'')||"
        + "coalesce(alamat,'')||' - '||coalesce(kota.nama_kota,'') "
        + "ilike '%"+txtSupplier.getText()+"%' order by 2" ;
        fn.lookup(evt, new Object[]{lblCustomer}, sQry, txtSupplier.getWidth()+lblCustomer.getWidth(), 300);
    }//GEN-LAST:event_txtSupplierKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        udfLoadData("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        HashMap param=new HashMap();
        param.put("idSupplier", fn.udfGetInt(txtSupplier.getText()));
        param.put("toko", MainForm.sToko);
        param.put("alamat1", MainForm.sAlamat1);
        param.put("alamat2", MainForm.sAlamat2);
        param.put("telp", MainForm.sTelp1);
        param.put("email", MainForm.sEmail);
        param.put("namaSupplier", lblCustomer.getText());

        service.cetakKartuHutang(param);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        bayar();
    }//GEN-LAST:event_btnBayarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private org.jdesktop.swingx.JXTable jXTable1;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JTextField txtSupplier;
    // End of variables declaration//GEN-END:variables
    
    private FocusListener txtFocusListener=new FocusListener() {
        public void focusGained(FocusEvent e) {
            if(e.getSource() instanceof JTextField || e.getSource() instanceof JFormattedTextField){
                ((JTextField)e.getSource()).setBackground(Color.YELLOW);
                if( (e.getSource() instanceof JTextField && ((JTextField)e.getSource()).getName()!=null && ((JTextField)e.getSource()).getName().equalsIgnoreCase("textEditor"))){
                    ((JTextField)e.getSource()).setSelectionStart(0);
                    ((JTextField)e.getSource()).setSelectionEnd(((JTextField)e.getSource()).getText().length());

                }
            }
        }

        public void focusLost(FocusEvent e) {
            if(e.getSource().getClass().getSimpleName().equalsIgnoreCase("JTextField")||
                    e.getSource().getClass().getSimpleName().equalsIgnoreCase("JFormattedTextField")){
                ((JTextField)e.getSource()).setBackground(Color.WHITE);
                
                if(e.getSource().equals(txtSupplier) && !fn.isListVisible()){
                    udfLoadData("");
                }
           }
        }
    } ;
}
