/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pos.ap;

import pos.ar.*;
import com.ustasoft.component.GeneralFunction;
import com.ustasoft.pos.dao.jdbc.ItemDao;
import com.ustasoft.pos.dao.jdbc.RelasiDao;
import com.ustasoft.pos.domain.Item;
import com.ustasoft.pos.domain.Relasi;
import com.ustasoft.pos.service.ReportService;
import java.sql.Connection;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import pos.MainForm;

/**
 *
 * @author cak-ust
 */
public class FrmRptPembelian extends javax.swing.JInternalFrame {
    private GeneralFunction fn=new GeneralFunction();
    ReportService service;
    private Connection conn;
    List lstGudang=new ArrayList();
    private List<Relasi> relasiList=new ArrayList<Relasi>();
    private List<Item> itemList=new ArrayList<Item>();
    /**
     * Creates new form FrmRptPenjualan
     */
    public FrmRptPembelian() {
        initComponents();
    }
    
    public void setConn(Connection con){
        this.conn=con;
    }

    private void initForm(){
        try {
            fn.setConn(this.conn);
            service=new ReportService(conn, this);
            
            Timestamp skg=fn.getTimeServer();
            jXDatePickerAwal.setDate(skg); jXDatePickerAwal.setFormats(MainForm.sDateFormat);
            jXDatePickerAkhir.setDate(skg);jXDatePickerAkhir.setFormats(MainForm.sDateFormat);
            jList1.setSelectedIndex(0);
            RelasiDao dao=new RelasiDao(conn);
            relasiList=dao.cariSemuaData(1);
            cmbSupplier.removeAllItems();
            cmbSupplier.addItem("");
            for(Relasi r: relasiList){
                cmbSupplier.addItem(r.getNamaRelasi());
            }
            
            ItemDao daoItem=new ItemDao(conn);
            itemList=daoItem.tampilkanData("");
            cmbItem.removeAllItems();
            cmbItem.addItem("");
            for(Item i: itemList){
                cmbItem.addItem(i.getNama_barang()+" "+i.getPlu());
            }
            AutoCompleteDecorator.decorate(cmbSupplier);
            AutoCompleteDecorator.decorate(cmbItem);
            
        } catch (Exception ex) {
            Logger.getLogger(FrmRptPenjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jXDatePickerAkhir = new org.jdesktop.swingx.JXDatePicker();
        jXDatePickerAwal = new org.jdesktop.swingx.JXDatePicker();
        jLabel4 = new javax.swing.JLabel();
        cmbSupplier = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cmbItem = new javax.swing.JComboBox();
        btnPreview = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setClosable(true);
        setTitle("Laporan Pembelian");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "1.  Transaksi Pembelian", "2.  Retur Pembelian", "3.  Pembelian Per Supplier", "4.  Rekap Transaksi Pembelian per Nota", "5.  Pembelian per Barang", "6.  Hutang Supplier", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameter"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Awal :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 20));

        jLabel3.setText("Supplier : ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 70, 20));
        jPanel2.add(jXDatePickerAkhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 50, 135, -1));
        jPanel2.add(jXDatePickerAwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 20, 135, -1));

        jLabel4.setText("Sampai :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 70, 20));

        cmbSupplier.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cmbSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 80, 225, -1));

        jLabel5.setText("Item : ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 105, 70, 20));

        cmbItem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cmbItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 105, 225, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, 200));

        btnPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/printer.png"))); // NOI18N
        btnPreview.setText("Tampilkan");
        btnPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewActionPerformed(evt);
            }
        });
        jPanel1.add(btnPreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 220, 100, 30));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/cancel.png"))); // NOI18N
        btnClose.setText("Tutup");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 220, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setBounds(0, 0, 649, 316);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewActionPerformed
        udfPreview();
    }//GEN-LAST:event_btnPreviewActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        initForm();;
    }//GEN-LAST:event_formInternalFrameOpened
    SimpleDateFormat fmt=new SimpleDateFormat("yyyy-MM-dd");
    
    private void udfPreview(){
        HashMap param=new HashMap();
        param.put("toko", MainForm.sToko);
        param.put("alamat1", MainForm.sAlamat1);
        param.put("alamat2", MainForm.sAlamat2);
        param.put("telp", MainForm.sTelp1);
        param.put("email", MainForm.sEmail);
        param.put("tanggal1", fmt.format(jXDatePickerAwal.getDate()));
        param.put("tanggal2", fmt.format(jXDatePickerAkhir.getDate()));
        param.put("idSupplier", cmbSupplier.getSelectedIndex()==0? null: relasiList.get(cmbSupplier.getSelectedIndex()-1).getIdRelasi() );
        param.put("namaSupplier", cmbSupplier.getSelectedIndex()==0? "": relasiList.get(cmbSupplier.getSelectedIndex()-1).getNamaRelasi());
        

        switch(jList1.getSelectedIndex()){
            case 0:{
                param.put("trxType", "PBL");
                service.udfPreview(param, "PembelianDetail", null);       break;
            }
            case 1:{
                param.put("trxType", "RBL");
                service.udfPreview(param, "PembelianDetail", null);       break;
            }
            case 2:{
                param.put("trxType", "");
                service.udfPreview(param, "PembelianDetailPerSupplier", null);       break;
            }
            case 3:{
                service.udfPreview(param, "PembelianRekapPerNota", null);        break;
            }
            case 4:{
                param.put("plu", cmbItem.getSelectedIndex()==0? "": itemList.get(cmbItem.getSelectedIndex()-1).getPlu());
                service.udfPreview(param, "PembelianDetailPerBarang", null);        break;
            }
            case 5:{
                service.udfPreview(param, "HutangSupplier", null);        break;
            }
            default:{
                break;
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnPreview;
    private javax.swing.JComboBox cmbItem;
    private javax.swing.JComboBox cmbSupplier;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerAkhir;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerAwal;
    // End of variables declaration//GEN-END:variables
}
